spring.application.name=Product
server.port=8082
spring.config.import=optional:configserver:http://localhost:9999/config

#spring.datasource.url= jdbc:postgresql://localhost:5433/employeeApp
#spring.datasource.username=postgres
#spring.datasource.password=root

