spring.application.name=servive-registery
server.port=8761

server.servlet.context-path=/registry
#To remove self registration of eureka server
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false